version: '3.7'
services:
  reversproxy:
    image: hub.cloudiolab.com/admin/nginx_reverse_proxy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/root_nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /docker_volumes/dhparam/hub.cloudiolab.com-dhparam-4096.pem:/etc/ssl/certs/hub.cloudiolab.com-dhparam-4096.pem
      - /docker_volumes/letsencrypt/etc/letsencrypt/live/hub.cloudiolab.com/fullchain.pem:/etc/letsencrypt/live/hub.cloudiolab.com/fullchain.pem
      - /docker_volumes/letsencrypt/etc/letsencrypt/live/hub.cloudiolab.com/privkey.pem:/etc/letsencrypt/live/hub.cloudiolab.com/privkey.pem
      - /docker_volumes/htpasswd/auth/htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - docker-reg
    networks:
      - common_network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  docker-reg:
    image: registry:latest
    ports:
      - "5000:5000"
    volumes:
      - /docker_volumes/docker_registry:/var/lib/registry:rw
    networks:
      - common_network
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  common_network: